services:

   Maris\SymfonyBundle\PersonBundle\:
      resource: '../../'
      exclude: '../../{DBAL,DependencyInjection,Entity,Form,ORM,Resources,Gender.php,PersonCompanyBundle.php}'

   #Maris\SymfonyBundle\PersonBundle\Repository\PersonRepository: