services:

  _defaults:
    autowire: true
    autoconfigure: true

  Maris\SymfonyBundle\PersonBundle\Repository\PersonRepository:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/ORM/'
