services:

  #_defaults:
  #  autowire: true      # Automatically injects dependencies in your services.
  #  autoconfigure: true

  Maris\SymfonyBundle\PersonBundle\:
    resource:
      - 'src/Repositories/'
