services:

   # конфигурация для сервисов по умолчанию в *этом* файле
   _defaults:
      autowire: true      # Автоматически внедряет зависимости в ваши сервисы.
      autoconfigure: true # Автоматически регистрирует ваши сервисы как команды, подписчики событий и т.д.

   Maris\SymfonyBundle\PersonBundle\:
      resource: '../../'
      exclude: '../../{DBAL,DependencyInjection,Entity,Form,ORM,Resources,Gender.php,PersonCompanyBundle.php}'

   #Maris\SymfonyBundle\PersonBundle\Repository\PersonRepository: